### ISSUE TITLE
Latest experimental release won't start from DTerm

### ISSUE THREAD

**Issue by johnthedebs** [brotherbard/gitx#49]
I've installed the latest experimental release of GitX (3.0.1), and I'm on OS X 10.6.4 with git 1.7.1.

When I run `gitx` from the command line it works great. If I try starting it from DTerm (http://www.decimus.net/dterm.php), which has always worked before, it just does nothing. No error, no GitX.

I've tried doing "Enable Terminal Usage..." a few times but that was no help.

**Comment by heipei** [comment]
What's the return-code? Are you sure 'gitx' is in your path? What does 'gitx -v' return?

**Comment by johnthedebs** [comment]
The return-code from DTerm is `0`
I ran `which gitx` from DTerm and got back `/usr/local/bin/gitx` (same as from iTerm)
`gitx -v` returns

```
GitX version 0.7.1 (v0.7.1-217-g5ddbcd1)
Using git found at /usr/local/git/bin/git, version 1.7.1
```

(also, same as from iTerm)

**Comment by brotherbard** [comment]
What version of GitX were you using that worked?

**Comment by johnthedebs** [comment]
The last experimental download you posted prior to 3.0.0 worked.

**Comment by brotherbard** [comment]
Should be fixed in SHA: 59c4983b5125a6ac27d961a20ab27f59fa1f3155 and is included in release 3.0.3

**Comment by johnthedebs** [comment]
I just updated to 3.0.3 and still have the problem. `gitx -v` outputs:

```
GitX version 0.7.1 (v0.7.1-232-gd00dbe4)
Using git found at /usr/local/git/bin/git, version 1.7.1
```

I'm assuming "d00dbe4" refers to a commit (the fix's parent); did you miss the commit with the fix when making the release?

**Comment by brotherbard** [comment]
Apparently I did. The correct one should be up now. Sorry about that.

**Comment by johnthedebs** [comment]
No worries, thanks for the quick fix!
